"""
Archivist Agent — Living Context Maintainer.

Produces and maintains the system's output artifacts as living documents
that can be re-used, updated, and injected into AI coding agents for
instant architectural awareness.

Artifacts produced:
  - CODEBASE.md   — Living context file for AI agent injection
  - onboarding_brief.md — Five FDE Day-One answers with evidence
  - cartography_trace.jsonl — Audit log of every analysis action
"""

from __future__ import annotations

import json
import logging
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.graph.knowledge_graph import KnowledgeGraph

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Trace Logger
# ---------------------------------------------------------------------------

class TraceLogger:
    """
    Structured audit logger for cartography analysis actions.

    Writes JSON-Lines to cartography_trace.jsonl with timestamp,
    agent name, action description, evidence source, and confidence.
    """

    def __init__(self, output_path: Path) -> None:
        self._path = output_path
        self._entries: list[dict[str, Any]] = []

    def log(
        self,
        agent: str,
        action: str,
        evidence_source: str = "static_analysis",
        confidence: float = 1.0,
        details: dict[str, Any] | None = None,
    ) -> None:
        """Record an analysis action."""
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "agent": agent,
            "action": action,
            "evidence_source": evidence_source,
            "confidence": confidence,
            "details": details or {},
        }
        self._entries.append(entry)

    def flush(self) -> None:
        """Write all buffered entries to the JSONL file."""
        self._path.parent.mkdir(parents=True, exist_ok=True)
        with self._path.open("a", encoding="utf-8") as f:
            for entry in self._entries:
                f.write(json.dumps(entry, default=str) + "\n")
        count = len(self._entries)
        self._entries.clear()
        logger.info("Trace log flushed: %d entries → %s", count, self._path)


# ---------------------------------------------------------------------------
# CODEBASE.md Generator
# ---------------------------------------------------------------------------

def generate_codebase_md(
    knowledge_graph: KnowledgeGraph,
    surveyor_results: dict[str, Any],
    hydrologist_results: dict[str, Any],
    semanticist_results: dict[str, Any],
) -> str:
    """
    Generate the CODEBASE.md living context file.

    Structured for direct injection into AI coding agents to give
    instant architectural awareness. Sections:
      - Architecture Overview
      - Critical Path (top modules by PageRank)
      - Data Sources & Sinks
      - Known Debt
      - High-Velocity Files
      - Module Purpose Index
    """
    sections: list[str] = []

    # Header
    sections.append("# CODEBASE.md — Living Architecture Context\n")
    sections.append(f"> Auto-generated by The Brownfield Cartographer on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n")
    sections.append("> Inject this file into any AI coding agent for instant architectural awareness.\n")

    # --- Architecture Overview ---
    graph_summary = knowledge_graph.summary()
    sections.append("## Architecture Overview\n")
    sections.append(
        f"This codebase contains **{graph_summary['modules']} source modules** "
        f"with **{graph_summary['functions']} functions** across "
        f"**{graph_summary['total_edges']} dependency edges**. "
        f"The data layer tracks **{graph_summary['datasets']} datasets** "
        f"connected by **{graph_summary['transformations']} transformations**."
    )
    if graph_summary["circular_dependencies"] > 0:
        sections.append(
            f"\n⚠️ **{graph_summary['circular_dependencies']} circular dependency group(s)** detected."
        )
    sections.append("")

    # --- Critical Path ---
    sections.append("## Critical Path (Top Modules by PageRank)\n")
    top_hubs = surveyor_results.get("top_architectural_hubs", [])
    if top_hubs:
        sections.append("| Rank | Module | PageRank Score |")
        sections.append("|------|--------|----------------|")
        for i, hub in enumerate(top_hubs[:10], 1):
            sections.append(f"| {i} | `{hub['path']}` | {hub['pagerank']:.4f} |")
    else:
        sections.append("_No PageRank data available._")
    sections.append("")

    # --- Data Sources & Sinks ---
    sections.append("## Data Sources & Sinks\n")
    sources = hydrologist_results.get("data_sources", [])
    sinks = hydrologist_results.get("data_sinks", [])

    if sources:
        sections.append("### Sources (data enters here)")
        for src in sources:
            sections.append(f"- `{src}`")
        sections.append("")

    if sinks:
        sections.append("### Sinks (data exits here)")
        for sink in sinks:
            sections.append(f"- `{sink}`")
        sections.append("")

    if not sources and not sinks:
        sections.append("_No data lineage detected._\n")

    # --- Known Debt ---
    sections.append("## Known Debt\n")
    circular_deps = surveyor_results.get("circular_dependencies", [])
    dead_code = surveyor_results.get("dead_code_candidates", [])
    doc_drift = semanticist_results.get("doc_drift_flags", {})

    debt_items = 0
    if circular_deps:
        sections.append("### Circular Dependencies")
        for cycle in circular_deps:
            sections.append(f"- {' → '.join(f'`{m}`' for m in cycle)}")
            debt_items += 1
        sections.append("")

    if dead_code:
        sections.append("### Dead Code Candidates")
        sections.append("_Modules with public symbols never imported elsewhere:_")
        for path in dead_code[:20]:
            sections.append(f"- `{path}`")
        debt_items += len(dead_code)
        sections.append("")

    if doc_drift:
        sections.append("### Documentation Drift")
        sections.append("_Modules where docstring contradicts actual implementation:_")
        for path, drifts in list(doc_drift.items())[:15]:
            for drift in drifts:
                sections.append(f"- `{path}`: {drift}")
                debt_items += 1
        sections.append("")

    if debt_items == 0:
        sections.append("_No significant technical debt detected._\n")

    # --- High-Velocity Files ---
    sections.append("## High-Velocity Files (Recent Change Hotspots)\n")
    velocity_files = surveyor_results.get("high_velocity_files", [])
    if velocity_files:
        sections.append("| File | Commits (30d) |")
        sections.append("|------|---------------|")
        for entry in velocity_files[:15]:
            sections.append(f"| `{entry['path']}` | {entry['commits_30d']} |")
    else:
        sections.append("_No recent git history available (likely a shallow clone)._")
    sections.append("")

    # --- Module Purpose Index ---
    purpose_statements = semanticist_results.get("purpose_statements", {})
    domain_clusters = semanticist_results.get("domain_clusters", {})

    if purpose_statements:
        sections.append("## Module Purpose Index\n")

        # Group by domain if available
        if domain_clusters:
            domains: dict[str, list[str]] = {}
            for path, domain in domain_clusters.items():
                domains.setdefault(domain, []).append(path)

            for domain, paths in sorted(domains.items()):
                sections.append(f"### Domain: {domain}\n")
                for path in sorted(paths):
                    purpose = purpose_statements.get(path, "_No purpose generated_")
                    sections.append(f"**`{path}`**: {purpose}\n")
        else:
            for path, purpose in sorted(purpose_statements.items()):
                sections.append(f"**`{path}`**: {purpose}\n")

    return "\n".join(sections)


# ---------------------------------------------------------------------------
# Onboarding Brief Generator
# ---------------------------------------------------------------------------

def generate_onboarding_brief(
    day_one_answers: dict[str, str],
    knowledge_graph: KnowledgeGraph,
    surveyor_results: dict[str, Any],
    hydrologist_results: dict[str, Any],
) -> str:
    """
    Generate the onboarding_brief.md — the FDE Day-One Brief.

    Formats the Five Day-One Answers with evidence citations and
    supplementary data from the knowledge graph.
    """
    sections: list[str] = []

    sections.append("# FDE Day-One Onboarding Brief\n")
    sections.append(f"> Generated by The Brownfield Cartographer on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n")
    sections.append("---\n")

    questions = {
        "q1": "What is the primary data ingestion path?",
        "q2": "What are the 3–5 most critical output datasets/endpoints?",
        "q3": "What is the blast radius if the most critical module fails?",
        "q4": "Where is the business logic concentrated vs. distributed?",
        "q5": "What has changed most frequently in the last 90 days (git velocity)?",
    }

    for key, question in questions.items():
        sections.append(f"## {question}\n")
        answer = day_one_answers.get(key, "_Answer not available — configure an LLM provider._")
        sections.append(f"{answer}\n")
        sections.append("---\n")

    # Supplementary data
    graph_summary = knowledge_graph.summary()
    sections.append("## Supplementary Metrics\n")
    sections.append(f"| Metric | Value |")
    sections.append(f"|--------|-------|")
    sections.append(f"| Total modules | {graph_summary['modules']} |")
    sections.append(f"| Total functions | {graph_summary['functions']} |")
    sections.append(f"| Total datasets | {graph_summary['datasets']} |")
    sections.append(f"| Total transformations | {graph_summary['transformations']} |")
    sections.append(f"| Circular dependencies | {graph_summary['circular_dependencies']} |")
    sections.append(f"| Graph nodes | {graph_summary['total_nodes']} |")
    sections.append(f"| Graph edges | {graph_summary['total_edges']} |")

    # Data sources & sinks summary
    sources = hydrologist_results.get("data_sources", [])
    sinks = hydrologist_results.get("data_sinks", [])
    if sources:
        sections.append(f"\n### Data Entry Points")
        for src in sources:
            sections.append(f"- `{src}`")
    if sinks:
        sections.append(f"\n### Data Exit Points")
        for sink in sinks:
            sections.append(f"- `{sink}`")

    sections.append("")
    return "\n".join(sections)


# ---------------------------------------------------------------------------
# Archivist Agent — Public API
# ---------------------------------------------------------------------------

class Archivist:
    """
    The Archivist agent produces and maintains living context artifacts.

    Generates CODEBASE.md, onboarding_brief.md, and manages the
    cartography_trace.jsonl audit log across all analysis phases.
    """

    def __init__(self) -> None:
        self.trace_logger: TraceLogger | None = None

    def init_trace(self, cartography_dir: Path) -> TraceLogger:
        """Initialize the trace logger for a new analysis run."""
        trace_path = cartography_dir / "cartography_trace.jsonl"
        # Clear previous trace for fresh runs
        if trace_path.exists():
            trace_path.unlink()
        self.trace_logger = TraceLogger(trace_path)
        return self.trace_logger

    def run(
        self,
        repo_root: Path,
        knowledge_graph: KnowledgeGraph,
        surveyor_results: dict[str, Any],
        hydrologist_results: dict[str, Any],
        semanticist_results: dict[str, Any],
        cartography_dir: Path,
    ) -> dict[str, Any]:
        """
        Generate all living context artifacts.

        Writes to the .cartography/ directory:
          - CODEBASE.md
          - onboarding_brief.md
          - cartography_trace.jsonl (flushed)
        """
        logger.info("Archivist: generating living context artifacts")
        start_time = time.monotonic()

        # Log the archivist's own start
        if self.trace_logger:
            self.trace_logger.log(
                agent="archivist",
                action="artifact_generation_started",
                details={"output_dir": str(cartography_dir)},
            )

        cartography_dir.mkdir(parents=True, exist_ok=True)

        # --- Generate CODEBASE.md ---
        codebase_md = generate_codebase_md(
            knowledge_graph,
            surveyor_results,
            hydrologist_results,
            semanticist_results,
        )
        codebase_path = cartography_dir / "CODEBASE.md"
        codebase_path.write_text(codebase_md, encoding="utf-8")
        logger.info("CODEBASE.md written → %s", codebase_path)

        if self.trace_logger:
            self.trace_logger.log(
                agent="archivist",
                action="codebase_md_generated",
                details={"path": str(codebase_path), "size_bytes": len(codebase_md)},
            )

        # --- Generate onboarding_brief.md ---
        day_one_answers = semanticist_results.get("day_one_answers", {})
        brief_md = generate_onboarding_brief(
            day_one_answers,
            knowledge_graph,
            surveyor_results,
            hydrologist_results,
        )
        brief_path = cartography_dir / "onboarding_brief.md"
        brief_path.write_text(brief_md, encoding="utf-8")
        logger.info("onboarding_brief.md written → %s", brief_path)

        if self.trace_logger:
            self.trace_logger.log(
                agent="archivist",
                action="onboarding_brief_generated",
                details={"path": str(brief_path), "size_bytes": len(brief_md)},
            )

        # --- Flush trace log ---
        elapsed = time.monotonic() - start_time
        if self.trace_logger:
            self.trace_logger.log(
                agent="archivist",
                action="artifact_generation_complete",
                details={"elapsed_seconds": round(elapsed, 2)},
            )
            self.trace_logger.flush()

        return {
            "artifacts_written": [
                str(codebase_path),
                str(brief_path),
            ],
            "codebase_md_size": len(codebase_md),
            "brief_md_size": len(brief_md),
            "elapsed_seconds": round(elapsed, 2),
        }
